version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:10
    environment:
    #  POSTGRES_USER: root
      POSTGRES_PASSWORD: younglinuxer
      PGDATA: /data/postgres
      TZ: Asia/Shanghai
    volumes:
       - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: younglinuxer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: younglinuxer
    volumes:
       - pgadmin:/root/.pgadmin
       - ./pg_storage:/var/lib/pgadmin/storage
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    pg_storage:
