brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0

deleteWhen=04
fileReservedTime=48

brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

# 关键：给外部客户端返回可访问的 Broker 地址
brokerIP1=10.100.17.34

# 可选，保持默认端口也可以不写
listenPort=10911

# 建议先打开自动创建 Topic，便于联调
autoCreateTopicEnable=true
