version: '3'
services:
  redis-master01:
    image: redis:5.0.8
    container_name: redis-master01
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./conf/node01.conf:/etc/redis/redis.conf
      - ./data:/data
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.10

  redis-master02:
    image: redis:5.0.8
    container_name: redis-master02
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./conf/node02.conf:/etc/redis/redis.conf
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.11

  redis-master03:
    image: redis:5.0.8
    container_name: redis-master03
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./conf/node03.conf:/etc/redis/redis.conf
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.12

  redis-slave01:
    image: redis:5.0.8
    container_name: redis-slave01
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6382:6379
    volumes:
      - ./conf/node04.conf:/etc/redis/redis.conf
      - ./data:/data
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.13

  redis-slave02:
    image: redis:5.0.8
    container_name: redis-slave02
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6383:6379
    volumes:
      - ./conf/node05.conf:/etc/redis/redis.conf
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.14

  redis-slave03:
    image: redis:5.0.8
    container_name: redis-slave03
    privileged: true
    hostname: redis
    restart: always
    ports:
      - 6384:6379
    volumes:
      - ./conf/node06.conf:/etc/redis/redis.conf
    command:
      redis-server  /etc/redis/redis.conf
    networks:
      proxy:
        ipv4_address: 172.16.8.15

networks:
  proxy:
    ipam:
      config:
      - subnet: 172.16.8.0/24