version: '3'

services:
  mysql-master:
    container_name: mysql-master       # 指定容器的名称
    image: mysql:5.7                   # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bGludXIK"
    volumes:
      - "./master-data:/var/lib/mysql"           # 挂载数据目录
      - "./config/master.cnf:/etc/mysql/my.cnf"      # 挂载配置文件
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime" #设置时区
  mysql-slave:
    container_name: mysql-slave       # 指定容器的名称
    image: mysql:5.7                   # 指定镜像和版本
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "eW91bmcK"
    volumes:
      - "./slave-data:/var/lib/mysql"           # 挂载数据目录
      - "./config/slave.cnf:/etc/mysql/my.cnf"      # 挂载配置文件
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime" #设置时区
