input {
  jdbc {
    jdbc_driver_library => "/tmp/mysql-connector-java-5.1.42.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://172.16.12.44:3306/rsp_server_deploy?useSSL=false"
    jdbc_user => "repl"
    jdbc_password => "eW91bm=#cK"
    #schedule ==> "* * 7 * *"
   # from two table join data
    #statement => "SELECT DISTINCT(service_catalogue.service_name),resources_catalogue.resource_name from service_catalogue left join resources_catalogue on  resources_catalogue.id = service_catalogue.resource_id;"
    statement => "SELECT DISTINCT(service_catalogue.service_name) as service_code ,resources_catalogue.resource_name as service_name from service_catalogue left join resources_catalogue on  resources_catalogue.id = service_catalogue.resource_id;"
  }
}



filter {

    mutate { convert => {"lat" => "float"} }
    mutate { convert => {"long" => "float"} }
    mutate { rename => {"lat" => "[location][lat]"} }
    mutate { rename => {"long" => "[location][lon]"} }


    date {
        locale => "eng"
        match => ["datetime", "yyyy-MM-dd HH:mm:ss", "ISO8601"]
        target => "datetime"
           } 
   
}

output{
   elasticsearch {
   hosts => ["172.16.12.88:9200"] 
   index => "szcq_api2"
   user => "elastic"
   password => "ZWxhc3RpY3NlYXJjaAo"
    

}
  stdout { codec => rubydebug { metadata => true } }
   # stdout { codec => dots }
}
