global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'

route:
  receiver: "alerta"
  group_by: ['alertname']
  group_wait:      30s
  group_interval:  30m
  repeat_interval: 2h

receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://10.1.34.13:39092/send'
    send_resolved: true


