version: '3'
services:
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
    environment:
     MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
     MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    volumes:
      - "./data:/data"